# Generated by Django 4.2.6 on 2023-10-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(default='day1', max_length=255)),
                ('breakfast', models.CharField(max_length=255)),
                ('lunch', models.CharField(max_length=255)),
                ('tea', models.CharField(max_length=255)),
                ('dinner', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('food', models.ManyToManyField(to='food.food')),
            ],
        ),
    ]
